apiVersion: v2
name: beskar7
description: A Helm chart for Beskar7 - Cluster API Infrastructure Provider for Immutable Bare Metal
type: application
version: 0.4.0-alpha
appVersion: "v0.4.0-alpha"
keywords:
  - cluster-api
  - infrastructure
  - bare-metal
  - redfish
  - kubernetes
home: https://github.com/wrkode/beskar7
sources:
  - https://github.com/wrkode/beskar7
maintainers:
  - name: wrkode
    url: https://github.com/wrkode
annotations:
  category: Infrastructure
